#!/usr/bin/env python

import re
import time
import requests
import json
import tomllib

with open('config-source-pixiv.toml', 'rb') as file:
    config = tomllib.load(file)

def request(offset):
    if config['nsfw']:
        nsfw = 'hide'
    else:
        nsfw = 'show'

    url = f'https://www.pixiv.net/ajax/user/{config["account"]["user_id"]}/illusts/bookmarks?tag=&offset={offset}&limit={config["max"]}&rest={nsfw}&lang=en'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/103.0',
        'Cookie': f'PHPSESSID={config["account"]["user_id"]}_{config["account"]["token"]}'
    }

    return requests.get(
        url,
        headers=headers
    ).json()

def transform(post):
    date = re.sub(r'\+.+', '', post['updateDate'].replace('-', '/').replace('T', '/').replace(':', '/'))

    return json.dumps({
        'title': post['title'],
        'uri': f'http://i.pximg.net/img-master/img/{date}/{post["id"]}_p0_master1200.jpg',
        'height': post['width'],
        'width': post['height'],
        'type': 'Image',
        'tags': post['tags']
        })

offset = 0
prevPosts = config['max']
while prevPosts >= config['max']:
    data = request(offset)

    offset += config['max']
    prevPosts = len(data['body']['works'])

    for post in data['body']['works']:
        # only images & undeleted works
        if post['illustType'] == 0 and post['updateDate'] != '1970-01-01T00:00:00+09:00':
            print(transform(post))

    time.sleep(int(config['request_delay']))


