#!/usr/bin/env python

import sys
import json

def has_tag(tags, desired):
    return any(tag == desired for tag in tags)

def has_tags(tags, desired):
    result = True

    for tag in desired:
        invert = False
        if tag.startswith('!'):
            invert = True
            tag = tag[1:]

        result = result and has_tag(tags, tag)
        if invert:
            result = not result
        if not result:
            return False

    return True

query = sys.argv[1]
tags = query.split(';')
tags = tags[:len(tags) - 1]
for line in sys.stdin:
    line = line.rstrip()
    if query == '':
        print(line)
        continue

    media = json.loads(line)
    if has_tags(media['tags'], tags):
        print(line)
