#!/usr/bin/env python

import sys
import json
import tomllib
from urllib.parse import urlparse, urlunparse

with open('config-transform-proxy.toml', 'rb') as file:
    config = tomllib.load(file)

for line in sys.stdin:
    media = json.loads(line)

    suffix = ""
    if media['source'] == "source-pixiv":
        suffix = "pixiv"
    if media['source'] == "source-kemono":
        suffix = "kemono"
    if media['source'] == "source-arxiv":
        suffix = "arxiv"

    uri = urlparse(media["uri"])
    if 'http' in uri.scheme:
        if uri.path == '':
            uri = uri._replace(path = '/')

        # its called an AUTHORITY not a "netloc". i hate this language
        # https://www.rfc-editor.org/rfc/rfc2396#section-3.2
        uri = uri._replace(netloc=config['proxy_authority'], path=suffix + uri.path)

    # "urlunparse".. really?
    media["uri"] = urlunparse(uri)

    print(json.dumps(media))
