#!/usr/bin/env python

import sys
import requests
import json
import tomllib
from xml.etree import ElementTree

with open('config-source-kemono.toml', 'rb') as file:
    config = tomllib.load(file)

def request(query):
    url = f'http://export.arxiv.org/api/query?max_results=20&search_query={query}'
    return requests.get(url).text

def transform(paper):
    return json.dumps({
        'title': paper.findtext('{*}title'),
        'uri': paper.find("{*}link[@title='pdf']").attrib['href'],
        'author': paper.findtext('.//{*}author/{*}name'),
        'summary': paper.findtext('{*}summary'),
        'type': 'PDF',
        })

def parse(text):
    root = ElementTree.fromstring(text)
    return root.findall('{*}entry')


query = sys.argv[1]
if query != "":
    for paper in parse(request(query)):
        print(transform(paper))

